# Generated by Django 3.0.1 on 2019-12-24 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Options',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=200, verbose_name='Option title')),
                ('value', models.BooleanField(verbose_name='Enabled')),
            ],
            options={
                'verbose_name': 'Option',
                'verbose_name_plural': 'Options',
            },
        ),
        migrations.CreateModel(
            name='Pushes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created time')),
                ('sent', models.DateTimeField(blank=True, null=True, verbose_name='Sent time')),
                ('title', models.CharField(db_index=True, max_length=50, verbose_name='Notification title')),
                ('text', models.TextField(verbose_name='Notification body')),
                ('is_sent', models.BooleanField(default=False, verbose_name='Sent')),
                ('count_sent', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Push notification',
                'verbose_name_plural': 'Push notifications',
            },
        ),
    ]
